config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  namespace :dashxxboard do
    root 'products#index'
    resources :products do
        post 'fetch', on: :member
        post 'fetchAll', on: :collection
        resources :yield_datas, as: :yields
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/product.rb
class Product < ActiveRecord::Base

	validates_uniqueness_of :product_name
	validates_presence_of :product_name
	validates_presence_of :product_type
	validates_presence_of :real_name
	validates_presence_of :fund_code
	validates_presence_of :platform

	has_many :yieldDatas
    after_create :fetch_one_year

    scope :hot, -> { order('yield_data desc, yield_date desc')}

	def fetch		
		FundWorker.perform_async(false, id, fund_code, 'y')
	end

	def fetch_one_year
		FundWorker.perform_async(true, id, fund_code, 'n')
	end

	def filter_fetch_data data
		# data过滤
		data
	end

	def update_recent_yield yield_data
		yield_arr = yield_data.split(',')
		begin
			update_attributes(yield_date: yield_arr[0],
							  yield_data: yield_arr[1],				
								 nh_data: yield_arr[2])	
		rescue ActiveRecord::RecordInvalid => invalid
			p invalid.record.errors
			p '*' * 40
		end
	end
end

app/models/yield_data.rb
class YieldData < ActiveRecord::Base
	validates :product_id, :yield_data, :yield_date, presence: true
	validates :product_id, uniqueness: {scope: :yield_date}
	
	belongs_to :product, counter_cache: true

	default_scope { order('id desc') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashxxboard/base_controller.rb
class Dashxxboard::BaseController < ApplicationController

	layout 'dashboard'

end

app/controllers/dashxxboard/products_controller.rb
class Dashxxboard::ProductsController < Dashxxboard::BaseController

	before_filter :find_product, :only => [:show, :fetch, :edit, :update]

	def index
		@products = Product.hot
	end

	def show
		@product.test_fetch
	end

	def fetch
		@product.fetch
		redirect_to dashxxboard_products_path, notice: "正在更新 #{@product_name} 数据, 5秒后刷新"
	end

	def fetchAll
		SchedulerFundWorker.perform_async
		redirect_to dashxxboard_products_path
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to dashxxboard_products_path, notice: "添加理财产品#{@product.product_name}成功"
		else
			render action: :new
		end		
	end

	def edit		
	end

	def update
		if @product.update_attributes product_params
			redirect_to dashxxboard_products_path
		else
			render action: :edit
		end
	end

	private
		def product_params
			params.require(:product).permit(:product_name, :real_name, :product_type,
				:platform, :url, :fund_code, :yield_data, :yield_date, :nh_data)
		end

		def find_product
			@product = Product.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def eastmoney_fund_url fund_code
		"http://fund.eastmoney.com/#{fund_code}.html"
	end
end

app/helpers/dashxxboard/products_helper.rb
module Dashxxboard::ProductsHelper
end

app/views/dashxxboard/products/_form.html.slim
- url = action_name == 'edit' ? dashxxboard_product_path(@product) : dashxxboard_products_path
= form_for @product, url: url, html: {class:"form-horizontal"} do |f|
  - if @product.errors.any?
    #error_explanation
      h2 = "#{pluralize(@product.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @product.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :product_name, '产品名', class: 'col-lg-3 control-label'
    .col-lg-7
      = f.text_field :product_name, class: 'form-control'
  .form-group
    = f.label :real_name, '真实名称', class: 'col-lg-3 control-label'
    .col-lg-7
      = f.text_field :real_name, class: 'form-control'
  .form-group
    = f.label :product_type, '产品类型', class: 'col-lg-3 control-label'
    .col-lg-7
      = f.text_field :product_type, value:'货币基金', class: 'form-control'
  .form-group
    = f.label :platform, '平台', class: 'col-lg-3 control-label'
    .col-lg-7
      = f.text_field :platform, class: 'form-control'
  .form-group
    = f.label :url, '来源', class: 'col-lg-3 control-label'
    .col-lg-7
      = f.text_field :url, class: 'form-control' 
  .form-group
    = f.label :fund_code, '编码(天天平台)', class: 'col-lg-3 control-label'
    .col-lg-7
      = f.text_field :fund_code, class: 'form-control'      
  - if action_name == 'edit'
    .form-group
      = f.label :show,'是否显示', class: 'col-lg-3 control-label'
      .col-lg-7
        = f.check_box :show, class: 'form-control'
  .actions = f.submit '保存'

app/views/dashxxboard/products/edit.html.slim
.container
  .row
    .col-md-12
			.bs-callout.bs-callout-info
				h4 修改      	
				
			== render 'form'

			p	= link_to '返回', dashxxboard_products_path, class: 'btn-small'

app/views/dashxxboard/products/index.html.slim
.container
  .row
     .col-md-12
      = link_to '新产品', new_dashxxboard_product_path, :class => 'btn btn-default pull-left'
      = link_to '更新', fetchAll_dashxxboard_products_path, :class => 'btn btn-default pull-left', method: 'post'

      table.table.table-bordered.table-hover.table-striped              
        tr
          th 
          th 交易平台
          th 包装名
          th 真实名字
          th 收益时间
          th 万份收益
          th 七日年华
          th 趋势          
          th(colspan=3) 操作
        - @products.each_with_index do |product, index|
          tr
            td = product.id
            td = product.platform
            td = link_to product.product_name, dashxxboard_product_path(product)
            td = link_to product.real_name, product.url, target: '_black'
            td = product.yield_date            
            td = product.yield_data
            td = product.nh_data            
            td = product.yield_data_count
            td = link_to '天天', eastmoney_fund_url(product.fund_code), target: '_black'
            td = link_to 'Edit', edit_dashxxboard_product_path(product)
            td = link_to 'Fetch', fetch_dashxxboard_product_path(product), method: :post

app/views/dashxxboard/products/new.html.slim
.container
  .row
    .col-md-12
			.bs-callout.bs-callout-info
				h4 新理财产品添加      	
				
			== render 'form'

			p	= link_to '返回', dashxxboard_products_path, class: 'btn-small'

app/views/dashxxboard/products/show.html.slim
= @product.product_name

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Financer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/dashboard.html.slim
doctype html
html
	head
		meta[chartype='utf-8']
		title 理财小帮手
		= stylesheet_link_tag 'application'
		= javascript_include_tag 'application'
		= csrf_meta_tags

	body		
		.nabar.navbar-fixed-top.navbar-inverse
			.container
				.navbar-header
					button.navbar-toggle[type='button' data-toggle="collapse" data-target=".navbar-collapse"]
						span.icon-bar 
						span.icon-bar 
						span.icon-bar 
					//a.navbar-brand[href='#'] 理财宝宝						
				.collapse.navbar-collapse
					ul.nav.navbar-nav
						li = link_to 'Products', dashxxboard_products_path
						li = link_to 'Sidekiq', '/sidekiq', target: '_blank'					
		== yield